### ISSUE TITLE
Zeres Plugin Library Update 1.2.27 appears to have broken "Running Locks"

### ISSUE THREAD

**Issue by tworkman08** [rileyio/chastikeyinfo#4]
Zeres Plugin Library updated and immediately running locks now shows "0" when local Cache updates. the two users shown below I know to be in active locks. Reloaded BD and reinstalled CKinfo. on Mac 11.0 with BD 0.0.259 and CKinfo 2.1.0

<img width="704" alt="Screen Shot 2020-12-04 at 12 39 18 AM" src="https://user-images.githubusercontent.com/10482116/101146404-cf753700-35cf-11eb-8420-e914e4ae28b8.png">
<img width="486" alt="Screen Shot 2020-12-04 at 12 41 09 AM" src="https://user-images.githubusercontent.com/10482116/101146409-d00dcd80-35cf-11eb-8855-6182956cfe49.png">
<img width="270" alt="Screen Shot 2020-12-04 at 12 41 32 AM" src="https://user-images.githubusercontent.com/10482116/101146411-d0a66400-35cf-11eb-9ba4-083d5b5453ae.png">

**Comment by rileyio** [comment]
Is this still an issue?

**Comment by rileyio** [comment]
As this has been working and without any further issues reported I will proceed with closing the issue.
