### ISSUE TITLE
Bug/Issue: Display information missing

### ISSUE THREAD

**Issue by DesertDog1178** [rileyio/chastikeyinfo#7]
**Describe the bug**
The display next to the name of people no longer works.

**To Reproduce**
Download the .js, do the api commands properly and get updated info but nothing shows when you click on people or when they type

**Expected behavior**
The display next to the name of people no longer works despite updating the chastikey information.

**Screenshots**

**Desktop (please complete the following information):**
BetterDiscord v1.0.0 (the complete redesign)

**Comment by Johanna-5** [comment]
Having the same issue with the plugin

**Comment by rileyio** [comment]
I found and fixed the issue in a development copy.  I'll push that out as an update to get it working again but also looking at a way to possibly future proof this issue against changes from disc updates.

**Comment by rileyio** [comment]
With the `2.1.3` (Commit: 17774868266d988eafb285bb8ab0a44b5619f50d) release functionality has been restored.
